
---
common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: footprint_dev

 
test:
  <<: *common
  database: footprint_test


production:
  <<: *common
  database: footprint
